### ISSUE TITLE
Discussion: Should an admin be able to add names to the speaker list for those who doesn't use the website?

### ISSUE THREAD

**Issue by Portals** [Tejpbit/talarlista#21]

**Comment by Kalior** [comment]
I think, and @Tejpbit please correct me here, that this is already possible?

**Comment by NeonNeon** [comment]
If you mean that The speaker can add an arbitrary name to the list I believe this already works

**Comment by Tejpbit** [comment]
Can confirm, already works.
An admin can add somebody to a speakers list. If the person already exists, then that person is added, otherwise, a new user is created and added.
