### ISSUE TITLE
Backend doesn't respond sometimes.

### ISSUE THREAD

**Issue by Tejpbit** [Tejpbit/talarlista#8]
It requires a restart to fix it.
I'm suspecting that the hub go routine gets stuck while trying to send something to a channel which isn't read.
Fix for this should be to buffer all channels which the hub routine sends to and create a timeout if the buffer gets full. If the buffer is full the user should be disconnected (maybe try to reconnect it?) and the channel dropped.

**Comment by mattiasnilsen** [comment]
This happens when you open more than one connection to the website from the same computer
